export const DAT_SECTIONS = [
  {
    name: "Biology",
    slug: "biology",
    icon: "🧬",
    color: "#16A34A",
    description: "Cell biology, genetics, anatomy, physiology, ecology, and evolution",
    datQuestions: 40,
    datMinutes: 90,
    chapters: 13,
  },
  {
    name: "General Chemistry",
    slug: "general-chemistry",
    icon: "⚗️",
    color: "#2563EB",
    description: "Atomic structure, bonding, thermodynamics, kinetics, equilibrium, acids & bases",
    datQuestions: 30,
    datMinutes: 90,
    chapters: 10,
  },
  {
    name: "Organic Chemistry",
    slug: "organic-chemistry",
    icon: "🔬",
    color: "#7C3AED",
    description: "Stereochemistry, reactions, mechanisms, functional groups, biochemistry basics",
    datQuestions: 30,
    datMinutes: 90,
    chapters: 10,
  },
  {
    name: "Perceptual Ability",
    slug: "perceptual-ability",
    icon: "🎯",
    color: "#DC2626",
    description: "Keyholes, views, angle ranking, hole punching, cube counting, pattern folding",
    datQuestions: 90,
    datMinutes: 60,
    chapters: 6,
  },
  {
    name: "Reading Comprehension",
    slug: "reading-comprehension",
    icon: "📖",
    color: "#D97706",
    description: "Scientific and humanities passages with comprehension questions",
    datQuestions: 50,
    datMinutes: 60,
    chapters: 4,
  },
  {
    name: "Quantitative Reasoning",
    slug: "quantitative-reasoning",
    icon: "📐",
    color: "#0891B2",
    description: "Algebra, geometry, trigonometry, probability, data analysis, word problems",
    datQuestions: 40,
    datMinutes: 45,
    chapters: 8,
  },
] as const;

export type SectionSlug = (typeof DAT_SECTIONS)[number]["slug"];
